### ISSUE TITLE
"The Lazy GM's Resource Document"の日本語化

### ISSUE THREAD

**Issue by mayosuke** [mayosuke/cult-of-slyflourish#4]
ブラッシュアップは後ほど行うので、まずは全体をざっと訳してしまう。

一通り日本語化できたセクションをチェックすること。

- [x] 冒頭部分
- [x] The Eight Steps of Lazy RPG Prep
- [x] The Lazy RPG Preparation Process
- [x] Example Strong Starts
- [x] Creating Secrets and Clues
- [x] Building an RPG Group
- [x] Session Zero Checklist
- [x] Safety Tools
- [x] Connecting Characters
- [x] Spiral Campaign Development
- [x] Quest Templates
- [x] Tools for 5e Improvisation
- [x] Quick Tricks for Lazier 5e Games
- [x] 5e Quick Encounter Building
- [x] Lazy Combat Encounter Building for 5e
- [x] Theater of the Mind Guidelines (Extended)
- [x] Theater of the Mind Guidelines (Abbreviated)
- [x] Zone-Based Combat
- [x] Monster Difficulty Dials
- [x] Running Hordes
- [x] Stress Effects
- [x] Core Adventure Generators
- [x] NPC Generator
- [x] Treasure Generator
- [x] Random Traps
- [x] Random Monuments
- [x] Random Items
- [x] Random Town Events
- [x] Random Dungeon Monsters
- [x] Lazy Solo 5e

**Comment by Hideatdrizzton** [comment]
上から順に進めています。来週中くらいまでにここまではできると思います。
 The Lazy RPG Preparation Process
 Example Strong Starts
 Creating Secrets and Clues
 Building an RPG Group

**Comment by mayosuke** [comment]
Theater of the Mind Guidelines (Abbreviated)
が終わりました。次はZone-Based Combatをやります。

**Comment by mayosuke** [comment]
GONさんがCore Adventure Generatorを翻訳中。

**Comment by mayosuke** [comment]
Zone-Based Combat
おわり。

**Comment by Hideatdrizzton** [comment]
Building an RPG Group　終了しました。

**Comment by pipechair** [comment]
Session Zero Checklist あたりから進めていきたいと思います。出遅れた。インストールしてたgitのバージョンが古くてHTTPSでのログオンが上手く言ってませんでした。

**Comment by mayosuke** [comment]
冒頭部分はひでさんが翻訳してくださり、プルリク(#9)内容レビュー中です。権利関係の記述があるので、少し時間をかけてレビューさせていただいてます。

**Comment by mayosuke** [comment]
以下完了。
冒頭部分（ひでさん）
Core Adventure Generators（GONさん）

**Comment by MightyGON** [comment]
Stress Effects 作業入ります。

**Comment by MightyGON** [comment]
Stress Effectsを一通り翻訳しましたが、1228行目の以下部分の翻訳自信なし。フォローお願いします。
Make sure you review the effects on the table during session zero to ensure they don't cross any players' lines of comfort.
↓
セッション中必ず効果がプレイヤーの快適なラインを0より超えないことを確認してください。

**Comment by mayosuke** [comment]
Stress Effects
の翻訳マージしました。

**Comment by mayosuke** [comment]
Example Strong Starts
の翻訳マージしました。

**Comment by Hideatdrizzton** [comment]
じゃこの辺りを。
Session Zero Checklist
Safety Tools

**Comment by mayosuke** [comment]
「ラジー」ー＞「ズボラ」ー＞「ラジー」のプルリクマージしました。

**Comment by mayosuke** [comment]
@pipechair Creating Secrets and Cluesのプルリクマージしました。

**Comment by mayosuke** [comment]
mayosukeは次「Monster Difficulty Dials」をやります。

**Comment by mayosuke** [comment]
@Hideatdrizzton 以下のプルリクマージしました。
 Session Zero Checklist
 Safety Tools

**Comment by mayosuke** [comment]
@Hideatdrizzton 以下のプルリクマージしました。
- Connecting Characters
- Spiral Campaign Development

**Comment by mayosuke** [comment]
"Running Hordes"おわり。

**Comment by mayosuke** [comment]
"Lazy Combat Encounter Building for 5e"は目次が訳されてただけだったのでチェックを外しました。

**Comment by mayosuke** [comment]
5e Quick Encounter Building
 Lazy Combat Encounter Building for 5e
やります。

**Comment by mayosuke** [comment]
@Hideatdrizzton Treasure Generatorマージしました。

**Comment by mayosuke** [comment]
5e Quick Encounter Building
Lazy Combat Encounter Building for 5e
ざっと訳してマージしました。

**Comment by mayosuke** [comment]
Random dungeon monsters
おわり。
